// onboarding.md: pay-after-approval. A candidate submits evidence for their RUN; an
// admin reviews it; approval sets campaigns.verifiedAt (the run's public/ballot flag)
// and locks the person's slug. A candidacy (campaign) is the verifiable unit — an
// aspirant has no leaders row. Payment (subscriptions) is a separate, later concern.
import { and, asc, count, desc, eq, ilike, inArray, isNull, or, type SQL } from 'drizzle-orm';
import { db } from '$lib/server/db';
import { campaigns, contacts, managers, positions, users, verifications } from '$lib/server/db/schema';
import { user as authUsers } from '$lib/server/db/auth.schema';
import { findNationalIdConflict, fullName, generateLeaderSlug, isSlugAvailable, slugify } from '$lib/server/leader';
import { notifyUser } from '$lib/server/notifications';
import { signoffComplete, type ManagerRoles } from '$lib/utils/campaignRoles';

export type VerificationRow = {
	verificationId: number;
	campaignId: number;
	userId: number;
	firstName: string;
	otherNames: string;
	slug: string | null;
	positionTitle: string;
	region: string;
	requestedAt: string;
	verifiedAt: string | null; // campaigns.verifiedAt — the run's live/public state
	outcome: 'approved' | 'rejected' | null; // null = pending
	notes: string | null; // admin's reason, shown on the row below a rejected request
	// Prefilled into the approval form's slug input: the person's existing public
	// URL once they have one, else a fresh autogenerated slug from their name (an
	// application stays slugless until approval mints its permanent URL).
	suggestedSlug: string;
};

/** This run's live pending (unreviewed) verification request, if any. */
export async function getPendingVerification(campaignId: number) {
	const [row] = await db
		.select({ id: verifications.id, requestedAt: verifications.requestedAt })
		.from(verifications)
		.where(and(eq(verifications.campaignId, campaignId), isNull(verifications.outcome)));
	return row ?? null;
}

/**
 * The reason (and when) behind this run's most recent rejection — but only when
 * their latest request is that rejection, i.e. they haven't re-submitted since.
 */
export async function getLatestRejection(campaignId: number) {
	const [row] = await db
		.select({ notes: verifications.notes, outcome: verifications.outcome, reviewedAt: verifications.reviewedAt })
		.from(verifications)
		.where(eq(verifications.campaignId, campaignId))
		.orderBy(desc(verifications.requestedAt))
		.limit(1);
	if (!row || row.outcome !== 'rejected') return null;
	return { notes: row.notes, reviewedAt: row.reviewedAt ? row.reviewedAt.toISOString() : null };
}

/** Submits a verification request for a run. Fails if one is already pending. */
export async function requestVerification(campaignId: number, requestedBy: number, evidence: Record<string, string>) {
	const existing = await getPendingVerification(campaignId);
	if (existing) return { ok: false as const, error: 'A verification request is already pending review.' };

	await db.insert(verifications).values({ campaignId, requestedBy, evidence });
	return { ok: true as const };
}

export type VerificationPage = { requests: VerificationRow[]; total: number };

// The columns the table header can sort by, mapped to their SQL expressions.
// `requested` is the default (newest first) — same as the old fixed order.
const VERIFICATION_SORTS = {
	position: positions.title,
	region: positions.region,
	user: users.firstName,
	requested: verifications.requestedAt,
	outcome: verifications.outcome
} as const;
export type VerificationSort = keyof typeof VERIFICATION_SORTS;

/** Every verification request ever made — searchable and sortable across ALL
 * pages (the WHERE/ORDER BY run in SQL, before LIMIT/OFFSET, so paging is
 * correct). `q` matches the person, their slug, and the seat; default order is
 * newest-requested-first. */
export async function listVerifications(
	page: number,
	pageSize: number,
	opts: { q?: string; sort?: VerificationSort; dir?: 'asc' | 'desc' } = {}
): Promise<VerificationPage> {
	const q = opts.q?.trim();
	// One ILIKE across the person, their URL, and the seat — the columns the row shows.
	const where: SQL | undefined = q
		? or(
				ilike(users.firstName, `%${q}%`),
				ilike(users.otherNames, `%${q}%`),
				ilike(users.slug, `%${q}%`),
				ilike(positions.title, `%${q}%`),
				ilike(positions.region, `%${q}%`)
			)
		: undefined;

	const sortCol = VERIFICATION_SORTS[opts.sort ?? 'requested'] ?? verifications.requestedAt;
	const orderBy = (opts.dir === 'asc' ? asc : desc)(sortCol);

	const [rows, [{ total }]] = await Promise.all([
		db
			.select({
				verificationId: verifications.id,
				campaignId: verifications.campaignId,
				userId: users.id,
				firstName: users.firstName,
				otherNames: users.otherNames,
				slug: users.slug,
				positionTitle: positions.title,
				region: positions.region,
				requestedAt: verifications.requestedAt,
				verifiedAt: campaigns.verifiedAt,
				outcome: verifications.outcome,
				notes: verifications.notes
			})
			.from(verifications)
			.innerJoin(campaigns, eq(verifications.campaignId, campaigns.id))
			.innerJoin(users, eq(campaigns.subjectUserId, users.id))
			.innerJoin(positions, eq(campaigns.positionId, positions.id))
			.where(where)
			.orderBy(orderBy)
			.limit(pageSize)
			.offset((page - 1) * pageSize),
		db
			.select({ total: count() })
			.from(verifications)
			.innerJoin(campaigns, eq(verifications.campaignId, campaigns.id))
			.innerJoin(users, eq(campaigns.subjectUserId, users.id))
			.innerJoin(positions, eq(campaigns.positionId, positions.id))
			.where(where)
	]);

	return {
		total,
		requests: await Promise.all(
			rows.map(async (r) => ({
				...r,
				requestedAt: r.requestedAt.toISOString(),
				verifiedAt: r.verifiedAt ? r.verifiedAt.toISOString() : null,
				// A verified person keeps their URL; an unapproved application has no slug
				// yet, so suggest a fresh collision-free one from their name for the admin.
				suggestedSlug: r.slug ?? (await generateLeaderSlug(fullName(r)))
			}))
		)
	};
}

export type VerificationExtras = NonNullable<Awaited<ReturnType<typeof getVerificationExtras>>>;

/**
 * The review-only extras for one request, shown inline on the admin verifications
 * table when a row expands: IEBC cert, team sign-offs, request history. The
 * profile/campaign themselves are previewed on their own pages (/[slug],
 * /[slug]/[year]) now, not duplicated here.
 */
export async function getVerificationExtras(verificationId: number) {
	const [request] = await db.select().from(verifications).where(eq(verifications.id, verificationId));
	if (!request) return null;

	const [campaign] = await db.select().from(campaigns).where(eq(campaigns.id, request.campaignId));
	if (!campaign) return null;

	const [teamRows, historyRows] = await Promise.all([
		db
			.select({
				userId: managers.userId,
				roles: managers.roles,
				firstName: users.firstName,
				otherNames: users.otherNames,
				idFrontUrl: users.idFrontUrl,
				idBackUrl: users.idBackUrl,
				// Fallback when this manager has no domain `contacts` row yet (e.g. never
				// went through /verify/email) — every account still has its login email.
				authEmail: authUsers.email
			})
			.from(managers)
			.innerJoin(users, eq(managers.userId, users.id))
			.innerJoin(authUsers, eq(users.authUserId, authUsers.id))
			.where(and(eq(managers.subjectUserId, campaign.subjectUserId), eq(managers.isActive, true), isNull(managers.deletedAt))),
		db
			.select({
				id: verifications.id,
				requestedAt: verifications.requestedAt,
				outcome: verifications.outcome,
				notes: verifications.notes,
				reviewedAt: verifications.reviewedAt,
				reviewerFirstName: users.firstName,
				reviewerOtherNames: users.otherNames
			})
			.from(verifications)
			.leftJoin(users, eq(verifications.reviewedBy, users.id))
			.where(eq(verifications.campaignId, request.campaignId))
			.orderBy(desc(verifications.requestedAt))
	]);

	// Each team member's own phone/email (their account, not the profile subject's) —
	// one grouped query across every manager, keyed by userId.
	const teamContactRows = teamRows.length
		? await db
				.select({ userId: contacts.userId, channel: contacts.channel, value: contacts.value })
				.from(contacts)
				.where(and(inArray(contacts.userId, teamRows.map((t) => t.userId)), isNull(contacts.deletedAt)))
		: [];
	const teamContactsByUser = new Map<number, { sms?: string; email?: string }>();
	for (const c of teamContactRows) {
		const entry = teamContactsByUser.get(c.userId) ?? {};
		if (c.channel === 'sms') entry.sms = c.value;
		if (c.channel === 'email') entry.email = c.value;
		teamContactsByUser.set(c.userId, entry);
	}

	return {
		iebcCertificateUrl: campaign.iebcCertificateUrl,
		team: await Promise.all(
			teamRows.map(async (t) => {
				const roles = (t.roles ?? {}) as ManagerRoles;
				const teamContact = teamContactsByUser.get(t.userId);
				const complete = signoffComplete(roles, t);
				return {
					name: fullName(t),
					title: roles.title ?? null,
					nationalId: roles.nationalId ?? null,
					idFrontUrl: t.idFrontUrl,
					idBackUrl: t.idBackUrl,
					signoffComplete: complete,
					// Flagged for the admin to decide — not a hard block on save (could be a
					// genuine duplicate account for the same person).
					nationalIdConflict: complete && roles.nationalId ? await findNationalIdConflict(roles.nationalId, t.userId) : null,
					isApplicant: t.userId === request.requestedBy,
					phone: teamContact?.sms ?? null,
					email: teamContact?.email ?? t.authEmail
				};
			})
		),
		requestHistory: historyRows.map((h) => ({
			id: h.id,
			requestedAt: h.requestedAt.toISOString(),
			outcome: h.outcome,
			notes: h.notes,
			reviewedAt: h.reviewedAt ? h.reviewedAt.toISOString() : null,
			reviewerName: h.reviewerFirstName ? `${h.reviewerFirstName} ${h.reviewerOtherNames}` : null
		}))
	};
}

/**
 * Admin decision on a request — re-reviewable at any time: approving sets
 * campaigns.verifiedAt (and locks the person's slug); rejecting an approved request
 * reverts it, clearing verifiedAt and taking the run back off the public pages.
 */
export async function reviewVerification(
	verificationId: number,
	adminUserId: number,
	outcome: 'approved' | 'rejected',
	notes: string,
	// The public URL to mint on approval — an application is slugless until now, so
	// approval is where its permanent slug is set (the admin edits the suggestion).
	slugInput?: string
) {
	const [request] = await db.select().from(verifications).where(eq(verifications.id, verificationId));
	if (!request) return { ok: false as const, error: 'Request not found.' };

	if (outcome === 'approved') {
		const [campaign] = await db.select().from(campaigns).where(eq(campaigns.id, request.campaignId));
		const [subject] = await db.select().from(users).where(eq(users.id, campaign.subjectUserId));

		// The slug the admin submitted (or the person's existing one). Approval is
		// gated on a real, available URL — a slugless application can't go public.
		const slug = slugify(slugInput ?? '') || subject.slug || '';
		if (!slug) return { ok: false as const, error: 'Enter a public URL (slug) before approving.' };
		if (!(await isSlugAvailable(slug, subject.id))) {
			return { ok: false as const, error: `The URL "/${slug}" is already taken. Pick a new one before approving.` };
		}
		if (slug !== subject.slug) {
			await db.update(users).set({ slug }).where(eq(users.id, subject.id));
		}

		await db.update(campaigns).set({ verifiedAt: new Date() }).where(eq(campaigns.id, request.campaignId));
	} else {
		await db.update(campaigns).set({ verifiedAt: null }).where(eq(campaigns.id, request.campaignId));
	}

	await db
		.update(verifications)
		.set({ outcome, notes: notes || null, reviewedBy: adminUserId, reviewedAt: new Date() })
		.where(eq(verifications.id, verificationId));

	await notifyUser(request.requestedBy, {
		kind: 'verification',
		title: outcome === 'approved' ? 'Your verification was approved' : 'Your verification was rejected',
		body:
			outcome === 'approved'
				? 'Congratulations! Your application was approved. Your run is now live and publicly visible.'
				: `Your leaders.ke verification application was rejected.${notes ? `\nReason: "${notes}"` : ''}`,
		href: '/dashboard'
	});

	return { ok: true as const };
}
